Repository soynatan/django-easy-audit, pull requests merged in 2020-05, with the labels that each got.

#136 Fix for Issue #62 use request.user in the request signal
  easyaudit/signals/request_signals.py
  easyaudit/tests/test_app/tests.py
Labels: bug

#134 Increase admin list panel performance by selecting related
  easyaudit/admin.py
  easyaudit/admin_helpers.py
Labels: database, enhancement

#127 Read only events admin
  README.md
  easyaudit/admin.py
  easyaudit/admin_helpers.py
  easyaudit/settings.py
  easyaudit/tests/test_app/tests.py
Labels: enhancement
